
DROP TABLE IF EXISTS person;

DROP SEQUENCE IF EXISTS seq1;

CREATE SEQUENCE seq1 START WITH 1;

CREATE TABLE person (
   id BIGINT NOT NULL PRIMARY KEY DEFAULT nextval('seq1'),
   name VARCHAR(255) NOT NULL,
   age int
);
