DROP SCHEMA public CASCADE;

CREATE SEQUENCE seq1;

CREATE TABLE PERSON (
       id BIGINT NOT NULL PRIMARY KEY,
       name VARCHAR(255) NOT NULL
);

INSERT INTO PERSON (id, name) VALUES (NEXT VALUE FOR seq1, 'Jane');
INSERT INTO PERSON (id, name) VALUES (NEXT VALUE FOR seq1, 'John');